[package]
name = "dice_roller"
version = "0.1.0"
authors = ["Chad Oakley <chadoakley@meta.com>"]
edition = "2024"
publish = false

[dependencies]
iced.workspace = true
getrandom = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
iced.workspace = true
iced.features = ["webgl"]
wasm-bindgen = "0.2"
